# Generated by Django 6.0 on 2025-12-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=50, verbose_name="客户姓名"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="电话")),
                ("address", models.TextField(verbose_name="地址")),
                ("items_info", models.TextField(verbose_name="购买清单")),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="总价"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "待付款"), (1, "已接单/配送中"), (2, "已完成")],
                        default=0,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="下单时间"),
                ),
            ],
            options={
                "verbose_name": "订单中心",
                "verbose_name_plural": "订单中心",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="纸品名称")),
                (
                    "spec",
                    models.CharField(default="箱", max_length=50, verbose_name="规格"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="单价(元)"
                    ),
                ),
                ("stock", models.IntegerField(default=100, verbose_name="库存")),
                (
                    "image_url",
                    models.TextField(
                        default="https://via.placeholder.com/150",
                        verbose_name="图片链接",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否上架"),
                ),
            ],
            options={
                "verbose_name": "商品管理",
                "verbose_name_plural": "商品管理",
            },
        ),
    ]
